spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:socketdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

logging:
  level:
    com.stomp.demo: DEBUG