spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/socket_db2?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: zz126578

logging:
  level:
    com.stomp.demo: DEBUG